language: php
sudo: required
dist: trusty

php:
  - 7.4

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE testing;'

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction

script:
  - php artisan key:generate
  - php artisan config:cache
  - vendor/bin/phpunit
